{% set name = "pm4py" %}
{% set version = "2.7.11.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pm4py-{{ version }}.tar.gz
  sha256: f655de1c9745546b0f4366c0fdfc635ca6bcdc75381a0701401453c546744a63

build:
  number: 0
  # cvxopt not available for s390x and win
  skip: true  # [s390x or win]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy <2
    - pandas
    - deprecation
    - networkx
    - python-graphviz
    - wheel
    - setuptools
    - intervaltree
    - lxml
    - matplotlib-base
    - pydotplus
    - pytz
    - scipy
    - tqdm
    - cvxopt  # [py<313]

test:
  imports:
    - pm4py
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pm4py.fit.fraunhofer.de
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Process mining for Python
  description: |
    pm4py is a python library that supports (state-of-the-art) process mining
    algorithms in python. It is open source (licensed under GPL) and intended
    to be used in both academia and industry projects. pm4py is a product of
    the Fraunhofer Institute for Applied Information Technology.
  doc_url: https://pm4py.fit.fraunhofer.de
  dev_url: https://github.com/pm4py/pm4py-source

extra:
  recipe-maintainers:
    - lorepirri
